#-------------------------------------------------
#
# Project created by QtCreator
#
#-------------------------------------------------

QT       += core gui xml opengl

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = log750_lab2
TEMPLATE = app


SOURCES += QGLViewer/camera.cpp \
           OBJLoader.cpp \
           QGLViewer/constraint.cpp \
           QGLViewer/frame.cpp \
           QGLViewer/keyFrameInterpolator.cpp \
           QGLViewer/manipulatedCameraFrame.cpp \
           QGLViewer/manipulatedFrame.cpp \
           QGLViewer/mouseGrabber.cpp \
           QGLViewer/qglviewer.cpp \
           QGLViewer/quaternion.cpp \
           QGLViewer/saveSnapshot.cpp \
           QGLViewer/vec.cpp \
           cube.cpp \
           irrKlang/plugins/ikpMP3/CIrrKlangAudioStreamLoaderMP3.cpp \
           irrKlang/plugins/ikpMP3/CIrrKlangAudioStreamMP3.cpp \
           irrKlang/plugins/ikpMP3/decoder/bits.c \
           irrKlang/plugins/ikpMP3/decoder/mpaudec.c \
           irrKlang/plugins/ikpMP3/ikpMP3.cpp \
           main.cpp \
           mainwindow.cpp \
           node.cpp \
           simpleViewer.cpp

HEADERS  += QGLViewer/camera.h \
            OBJLoader.h \
            QGLViewer/config.h \
            QGLViewer/constraint.h \
            QGLViewer/domUtils.h \
            QGLViewer/frame.h \
            QGLViewer/keyFrameInterpolator.h \
            QGLViewer/manipulatedCameraFrame.h \
            QGLViewer/manipulatedFrame.h \
            QGLViewer/mouseGrabber.h \
            QGLViewer/qglviewer.h \
            QGLViewer/quaternion.h \
            QGLViewer/vec.h \
            cube.h \
            irrKlang/include/ik_ESoundEngineOptions.h \
            irrKlang/include/ik_ESoundOutputDrivers.h \
            irrKlang/include/ik_EStreamModes.h \
            irrKlang/include/ik_IAudioRecorder.h \
            irrKlang/include/ik_IAudioStream.h \
            irrKlang/include/ik_IAudioStreamLoader.h \
            irrKlang/include/ik_IFileFactory.h \
            irrKlang/include/ik_IFileReader.h \
            irrKlang/include/ik_IRefCounted.h \
            irrKlang/include/ik_ISound.h \
            irrKlang/include/ik_ISoundDeviceList.h \
            irrKlang/include/ik_ISoundEffectControl.h \
            irrKlang/include/ik_ISoundEngine.h \
            irrKlang/include/ik_ISoundMixedOutputReceiver.h \
            irrKlang/include/ik_ISoundSource.h \
            irrKlang/include/ik_ISoundStopEventReceiver.h \
            irrKlang/include/ik_IVirtualRefCounted.h \
            irrKlang/include/ik_SAudioStreamFormat.h \
            irrKlang/include/ik_irrKlangTypes.h \
            irrKlang/include/ik_vec3d.h \
            irrKlang/include/irrKlang.h \
            irrKlang/plugins/ikpMP3/CIrrKlangAudioStreamLoaderMP3.h \
            irrKlang/plugins/ikpMP3/CIrrKlangAudioStreamMP3.h \
            irrKlang/plugins/ikpMP3/decoder/internal.h \
            irrKlang/plugins/ikpMP3/decoder/mpaudec.h \
            irrKlang/plugins/ikpMP3/decoder/mpaudectab.h \
            irrKlang/plugins/ikpMP3/decoder/mpegaudio.h \
            mainwindow.h \
            node.h \
            simpleViewer.h

DISTFILES += \
    appear.wav \
    assets/README.txt \
    assets/Thumbs.db \
    assets/assets/README.txt \
    assets/assets/Thumbs.db \
    assets/assets/dry_ground.jpg \
    assets/assets/granite_floor.jpg \
    assets/assets/grass2.jpg \
    assets/assets/limestone_wall.jpg \
    assets/assets/pierre_bouchardee.jpg \
    assets/assets/wood_floor.jpg \
    assets/dry_ground.jpg \
    assets/dry_ground_normals.jpg \
    assets/granite_floor.jpg \
    assets/granite_floor_normals.jpg \
    assets/grass2.jpg \
    assets/grass_normals.jpg \
    assets/limestone_wall.jpg \
    assets/limestone_wall_normals.jpg \
    assets/pierre_bouchardee.jpg \
    assets/pierre_bouchardee_normals.jpg \
    assets/tournevis.mtl \
    assets/tournevis.obj \
    assets/wood_floor.jpg \
    assets/wood_floor_normals.jpg \
    basicShader.frag \
    basicShader.vert \
    constantColor.frag \
    constantColor.vert \
    explosion.wav \
    irrKlang/bin/dotnet-4-64/CSharp.01.HelloWorld.exe \
    irrKlang/bin/dotnet-4-64/CSharp.02.3DSound.exe \
    irrKlang/bin/dotnet-4-64/CSharp.03.MemoryPlayback.exe \
    irrKlang/bin/dotnet-4-64/CSharp.04.OverrideFileAccess.exe \
    irrKlang/bin/dotnet-4-64/CSharp.Winforms.Musicplayer.exe \
    irrKlang/bin/dotnet-4-64/ikpFlac.dll \
    irrKlang/bin/dotnet-4-64/ikpMP3.dll \
    irrKlang/bin/dotnet-4-64/irrKlang.NET4.dll \
    irrKlang/bin/linux-gcc-64/ikpFlac.so \
    irrKlang/bin/linux-gcc-64/ikpMP3.so \
    irrKlang/bin/linux-gcc-64/libIrrKlang.so \
    irrKlang/bin/macosx-gcc/01.HelloWorld \
    irrKlang/bin/macosx-gcc/02.3DSound \
    irrKlang/bin/macosx-gcc/03.MemoryPlayback \
    irrKlang/bin/macosx-gcc/04.OverrideFileAccess \
    irrKlang/bin/macosx-gcc/05.Effects \
    irrKlang/bin/macosx-gcc/MusicPlayer \
    irrKlang/bin/macosx-gcc/ikpFLAC.dylib \
    irrKlang/bin/macosx-gcc/ikpMP3.dylib \
    irrKlang/bin/macosx-gcc/libirrklang.dylib \
    irrKlang/bin/macosx-gcc/run_01_Helloworld.sh.command \
    irrKlang/bin/macosx-gcc/run_02_3DSound.sh.command \
    irrKlang/bin/macosx-gcc/run_03_MemoryPlayback.sh.command \
    irrKlang/bin/macosx-gcc/run_04_OverrideFileAccess.command \
    irrKlang/bin/macosx-gcc/run_05_Effects.command \
    irrKlang/bin/macosx-gcc/run_MusicPlayer.command \
    irrKlang/bin/winx64-visualStudio/01.HelloWorld.exe \
    irrKlang/bin/winx64-visualStudio/02.3DSound.exe \
    irrKlang/bin/winx64-visualStudio/03.MemoryPlayback.exe \
    irrKlang/bin/winx64-visualStudio/04.OverrideFileAccess.exe \
    irrKlang/bin/winx64-visualStudio/05.Effects.exe \
    irrKlang/bin/winx64-visualStudio/06.Recording.exe \
    irrKlang/bin/winx64-visualStudio/ikpFlac.dll \
    irrKlang/bin/winx64-visualStudio/ikpMP3.dll \
    irrKlang/bin/winx64-visualStudio/irrKlang.dll \
    irrKlang/changes.txt \
    irrKlang/doc/cpp/annotated.html \
    irrKlang/doc/cpp/classes.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_audio_recorder-members.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_audio_recorder.gif \
    irrKlang/doc/cpp/classirrklang_1_1_i_audio_recorder.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_audio_stream-members.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_audio_stream.gif \
    irrKlang/doc/cpp/classirrklang_1_1_i_audio_stream.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_audio_stream_loader-members.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_audio_stream_loader.gif \
    irrKlang/doc/cpp/classirrklang_1_1_i_audio_stream_loader.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_captured_audio_data_receiver-members.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_captured_audio_data_receiver.gif \
    irrKlang/doc/cpp/classirrklang_1_1_i_captured_audio_data_receiver.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_file_factory-members.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_file_factory.gif \
    irrKlang/doc/cpp/classirrklang_1_1_i_file_factory.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_file_reader-members.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_file_reader.gif \
    irrKlang/doc/cpp/classirrklang_1_1_i_file_reader.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_ref_counted-members.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_ref_counted.gif \
    irrKlang/doc/cpp/classirrklang_1_1_i_ref_counted.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_sound-members.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_sound.gif \
    irrKlang/doc/cpp/classirrklang_1_1_i_sound.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_sound_device_list-members.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_sound_device_list.gif \
    irrKlang/doc/cpp/classirrklang_1_1_i_sound_device_list.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_sound_effect_control-members.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_sound_effect_control.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_sound_engine-members.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_sound_engine.gif \
    irrKlang/doc/cpp/classirrklang_1_1_i_sound_engine.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_sound_mixed_output_receiver-members.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_sound_mixed_output_receiver.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_sound_source-members.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_sound_source.gif \
    irrKlang/doc/cpp/classirrklang_1_1_i_sound_source.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_sound_stop_event_receiver-members.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_sound_stop_event_receiver.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_virtual_ref_counted-members.html \
    irrKlang/doc/cpp/classirrklang_1_1_i_virtual_ref_counted.gif \
    irrKlang/doc/cpp/classirrklang_1_1_i_virtual_ref_counted.html \
    irrKlang/doc/cpp/classirrklang_1_1vec3d-members.html \
    irrKlang/doc/cpp/classirrklang_1_1vec3d.html \
    irrKlang/doc/cpp/doxygen.css \
    irrKlang/doc/cpp/doxygen.png \
    irrKlang/doc/cpp/files.html \
    irrKlang/doc/cpp/functions.html \
    irrKlang/doc/cpp/functions_0x63.html \
    irrKlang/doc/cpp/functions_0x64.html \
    irrKlang/doc/cpp/functions_0x65.html \
    irrKlang/doc/cpp/functions_0x66.html \
    irrKlang/doc/cpp/functions_0x67.html \
    irrKlang/doc/cpp/functions_0x69.html \
    irrKlang/doc/cpp/functions_0x6c.html \
    irrKlang/doc/cpp/functions_0x6e.html \
    irrKlang/doc/cpp/functions_0x6f.html \
    irrKlang/doc/cpp/functions_0x70.html \
    irrKlang/doc/cpp/functions_0x72.html \
    irrKlang/doc/cpp/functions_0x73.html \
    irrKlang/doc/cpp/functions_0x75.html \
    irrKlang/doc/cpp/functions_0x76.html \
    irrKlang/doc/cpp/functions_0x78.html \
    irrKlang/doc/cpp/functions_0x79.html \
    irrKlang/doc/cpp/functions_0x7a.html \
    irrKlang/doc/cpp/functions_0x7e.html \
    irrKlang/doc/cpp/functions_func.html \
    irrKlang/doc/cpp/functions_vars.html \
    irrKlang/doc/cpp/globals.html \
    irrKlang/doc/cpp/globals_defs.html \
    irrKlang/doc/cpp/hierarchy.html \
    irrKlang/doc/cpp/ik___e_sound_engine_options_8h.html \
    irrKlang/doc/cpp/ik___e_sound_engine_options_8h_source.html \
    irrKlang/doc/cpp/ik___e_sound_output_drivers_8h.html \
    irrKlang/doc/cpp/ik___e_sound_output_drivers_8h_source.html \
    irrKlang/doc/cpp/ik___e_stream_modes_8h.html \
    irrKlang/doc/cpp/ik___e_stream_modes_8h_source.html \
    irrKlang/doc/cpp/ik___i_audio_recorder_8h.html \
    irrKlang/doc/cpp/ik___i_audio_recorder_8h_source.html \
    irrKlang/doc/cpp/ik___i_audio_stream_8h.html \
    irrKlang/doc/cpp/ik___i_audio_stream_8h_source.html \
    irrKlang/doc/cpp/ik___i_audio_stream_loader_8h.html \
    irrKlang/doc/cpp/ik___i_audio_stream_loader_8h_source.html \
    irrKlang/doc/cpp/ik___i_file_factory_8h.html \
    irrKlang/doc/cpp/ik___i_file_factory_8h_source.html \
    irrKlang/doc/cpp/ik___i_file_reader_8h.html \
    irrKlang/doc/cpp/ik___i_file_reader_8h_source.html \
    irrKlang/doc/cpp/ik___i_ref_counted_8h.html \
    irrKlang/doc/cpp/ik___i_ref_counted_8h_source.html \
    irrKlang/doc/cpp/ik___i_sound_8h.html \
    irrKlang/doc/cpp/ik___i_sound_8h_source.html \
    irrKlang/doc/cpp/ik___i_sound_device_list_8h.html \
    irrKlang/doc/cpp/ik___i_sound_device_list_8h_source.html \
    irrKlang/doc/cpp/ik___i_sound_effect_control_8h.html \
    irrKlang/doc/cpp/ik___i_sound_effect_control_8h_source.html \
    irrKlang/doc/cpp/ik___i_sound_engine_8h.html \
    irrKlang/doc/cpp/ik___i_sound_engine_8h_source.html \
    irrKlang/doc/cpp/ik___i_sound_mixed_output_receiver_8h.html \
    irrKlang/doc/cpp/ik___i_sound_mixed_output_receiver_8h_source.html \
    irrKlang/doc/cpp/ik___i_sound_source_8h.html \
    irrKlang/doc/cpp/ik___i_sound_source_8h_source.html \
    irrKlang/doc/cpp/ik___i_sound_stop_event_receiver_8h.html \
    irrKlang/doc/cpp/ik___i_sound_stop_event_receiver_8h_source.html \
    irrKlang/doc/cpp/ik___i_virtual_ref_counted_8h.html \
    irrKlang/doc/cpp/ik___i_virtual_ref_counted_8h_source.html \
    irrKlang/doc/cpp/ik___s_audio_stream_format_8h.html \
    irrKlang/doc/cpp/ik___s_audio_stream_format_8h_source.html \
    irrKlang/doc/cpp/ik__irr_klang_types_8h.html \
    irrKlang/doc/cpp/ik__irr_klang_types_8h_source.html \
    irrKlang/doc/cpp/ik__vec3d_8h.html \
    irrKlang/doc/cpp/ik__vec3d_8h_source.html \
    irrKlang/doc/cpp/index.html \
    irrKlang/doc/cpp/installdox \
    irrKlang/doc/cpp/irr_klang_8h.html \
    irrKlang/doc/cpp/irr_klang_8h_source.html \
    irrKlang/doc/cpp/irrklang.png \
    irrKlang/doc/cpp/logobig.png \
    irrKlang/doc/cpp/namespaceirrklang.html \
    irrKlang/doc/cpp/namespacemembers.html \
    irrKlang/doc/cpp/namespacemembers_enum.html \
    irrKlang/doc/cpp/namespacemembers_eval.html \
    irrKlang/doc/cpp/namespacemembers_func.html \
    irrKlang/doc/cpp/namespacemembers_type.html \
    irrKlang/doc/cpp/namespacemembers_vars.html \
    irrKlang/doc/cpp/namespaces.html \
    irrKlang/doc/cpp/search/all_61.html \
    irrKlang/doc/cpp/search/all_63.html \
    irrKlang/doc/cpp/search/all_64.html \
    irrKlang/doc/cpp/search/all_65.html \
    irrKlang/doc/cpp/search/all_66.html \
    irrKlang/doc/cpp/search/all_67.html \
    irrKlang/doc/cpp/search/all_69.html \
    irrKlang/doc/cpp/search/all_6c.html \
    irrKlang/doc/cpp/search/all_6d.html \
    irrKlang/doc/cpp/search/all_6e.html \
    irrKlang/doc/cpp/search/all_6f.html \
    irrKlang/doc/cpp/search/all_70.html \
    irrKlang/doc/cpp/search/all_72.html \
    irrKlang/doc/cpp/search/all_73.html \
    irrKlang/doc/cpp/search/all_75.html \
    irrKlang/doc/cpp/search/all_76.html \
    irrKlang/doc/cpp/search/all_78.html \
    irrKlang/doc/cpp/search/all_79.html \
    irrKlang/doc/cpp/search/all_7a.html \
    irrKlang/doc/cpp/search/all_7e.html \
    irrKlang/doc/cpp/search/classes_69.html \
    irrKlang/doc/cpp/search/classes_73.html \
    irrKlang/doc/cpp/search/classes_76.html \
    irrKlang/doc/cpp/search/close.png \
    irrKlang/doc/cpp/search/defines_69.html \
    irrKlang/doc/cpp/search/enums_65.html \
    irrKlang/doc/cpp/search/enumvalues_65.html \
    irrKlang/doc/cpp/search/files_69.html \
    irrKlang/doc/cpp/search/functions_61.html \
    irrKlang/doc/cpp/search/functions_63.html \
    irrKlang/doc/cpp/search/functions_64.html \
    irrKlang/doc/cpp/search/functions_65.html \
    irrKlang/doc/cpp/search/functions_66.html \
    irrKlang/doc/cpp/search/functions_67.html \
    irrKlang/doc/cpp/search/functions_69.html \
    irrKlang/doc/cpp/search/functions_6c.html \
    irrKlang/doc/cpp/search/functions_6d.html \
    irrKlang/doc/cpp/search/functions_6e.html \
    irrKlang/doc/cpp/search/functions_6f.html \
    irrKlang/doc/cpp/search/functions_70.html \
    irrKlang/doc/cpp/search/functions_72.html \
    irrKlang/doc/cpp/search/functions_73.html \
    irrKlang/doc/cpp/search/functions_75.html \
    irrKlang/doc/cpp/search/functions_76.html \
    irrKlang/doc/cpp/search/functions_7e.html \
    irrKlang/doc/cpp/search/namespaces_69.html \
    irrKlang/doc/cpp/search/nomatches.html \
    irrKlang/doc/cpp/search/search.css \
    irrKlang/doc/cpp/search/search.js \
    irrKlang/doc/cpp/search/search.png \
    irrKlang/doc/cpp/search/typedefs_69.html \
    irrKlang/doc/cpp/search/typedefs_76.html \
    irrKlang/doc/cpp/search/variables_63.html \
    irrKlang/doc/cpp/search/variables_66.html \
    irrKlang/doc/cpp/search/variables_69.html \
    irrKlang/doc/cpp/search/variables_70.html \
    irrKlang/doc/cpp/search/variables_73.html \
    irrKlang/doc/cpp/search/variables_78.html \
    irrKlang/doc/cpp/search/variables_79.html \
    irrKlang/doc/cpp/search/variables_7a.html \
    irrKlang/doc/cpp/structirrklang_1_1_s_audio_stream_format-members.html \
    irrKlang/doc/cpp/structirrklang_1_1_s_audio_stream_format.html \
    irrKlang/doc/cpp/structirrklang_1_1_s_internal_audio_interface-members.html \
    irrKlang/doc/cpp/structirrklang_1_1_s_internal_audio_interface.html \
    irrKlang/doc/cpp/tab_b.gif \
    irrKlang/doc/cpp/tab_l.gif \
    irrKlang/doc/cpp/tab_r.gif \
    irrKlang/doc/cpp/tabs.css \
    irrKlang/doc/doc_cpp.html \
    irrKlang/doc/doc_dotnet.html \
    irrKlang/doc/dotnet/IrrKlang.AudioFormat.BytesPerSecond.html \
    irrKlang/doc/dotnet/IrrKlang.AudioFormat.ChannelCount.html \
    irrKlang/doc/dotnet/IrrKlang.AudioFormat.Format.html \
    irrKlang/doc/dotnet/IrrKlang.AudioFormat.FrameCount.html \
    irrKlang/doc/dotnet/IrrKlang.AudioFormat.FrameSize.html \
    irrKlang/doc/dotnet/IrrKlang.AudioFormat.SampleDataSize.html \
    irrKlang/doc/dotnet/IrrKlang.AudioFormat.SampleRate.html \
    irrKlang/doc/dotnet/IrrKlang.AudioFormat.SampleSize.html \
    irrKlang/doc/dotnet/IrrKlang.AudioFormat.html \
    irrKlang/doc/dotnet/IrrKlang.AudioFormatConstructor.html \
    irrKlang/doc/dotnet/IrrKlang.AudioFormatFields.html \
    irrKlang/doc/dotnet/IrrKlang.AudioFormatMembers.html \
    irrKlang/doc/dotnet/IrrKlang.AudioFormatProperties.html \
    irrKlang/doc/dotnet/IrrKlang.EventForwarder.html \
    irrKlang/doc/dotnet/IrrKlang.EventForwarderMembers.html \
    irrKlang/doc/dotnet/IrrKlang.FileFactoryForwarder.html \
    irrKlang/doc/dotnet/IrrKlang.FileFactoryForwarderMembers.html \
    irrKlang/doc/dotnet/IrrKlang.IAudioRecorder.AddSoundSourceFromRecordedAudio.html \
    irrKlang/doc/dotnet/IrrKlang.IAudioRecorder.AudioFormat.html \
    irrKlang/doc/dotnet/IrrKlang.IAudioRecorder.ClearRecordedAudioDataBuffer.html \
    irrKlang/doc/dotnet/IrrKlang.IAudioRecorder.Finalize.html \
    irrKlang/doc/dotnet/IrrKlang.IAudioRecorder.IsRecording.html \
    irrKlang/doc/dotnet/IrrKlang.IAudioRecorder.RecordedAudioData.html \
    irrKlang/doc/dotnet/IrrKlang.IAudioRecorder.StartRecordingBufferedAudio_overload_1.html \
    irrKlang/doc/dotnet/IrrKlang.IAudioRecorder.StartRecordingBufferedAudio_overload_2.html \
    irrKlang/doc/dotnet/IrrKlang.IAudioRecorder.StartRecordingBufferedAudio_overloads.html \
    irrKlang/doc/dotnet/IrrKlang.IAudioRecorder.StopRecordingAudio.html \
    irrKlang/doc/dotnet/IrrKlang.IAudioRecorder.html \
    irrKlang/doc/dotnet/IrrKlang.IAudioRecorderConstructor.html \
    irrKlang/doc/dotnet/IrrKlang.IAudioRecorderConstructor1.html \
    irrKlang/doc/dotnet/IrrKlang.IAudioRecorderConstructor2.html \
    irrKlang/doc/dotnet/IrrKlang.IAudioRecorderConstructor3.html \
    irrKlang/doc/dotnet/IrrKlang.IAudioRecorderMembers.html \
    irrKlang/doc/dotnet/IrrKlang.IAudioRecorderMethods.html \
    irrKlang/doc/dotnet/IrrKlang.IAudioRecorderProperties.html \
    irrKlang/doc/dotnet/IrrKlang.IFileFactory.html \
    irrKlang/doc/dotnet/IrrKlang.IFileFactory.openFile.html \
    irrKlang/doc/dotnet/IrrKlang.IFileFactoryMembers.html \
    irrKlang/doc/dotnet/IrrKlang.IFileFactoryMethods.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.Dispose.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.Finalize.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.Finished.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.Looped.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.MaxDistance.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.MinDistance.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.Pan.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.Paused.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.PlayLength.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.PlayPosition.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.PlaybackSpeed.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.Position.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.SoundEffectControl.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.Stop.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.Velocity.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.Volume.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.setSoundStopEventReceiver_overload_1.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.setSoundStopEventReceiver_overload_2.html \
    irrKlang/doc/dotnet/IrrKlang.ISound.setSoundStopEventReceiver_overloads.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundConstructor.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundDeviceList.DeviceCount.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundDeviceList.Finalize.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundDeviceList.getDeviceDescription.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundDeviceList.getDeviceID.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundDeviceList.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundDeviceListConstructor.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundDeviceListConstructor1.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundDeviceListConstructor2.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundDeviceListMembers.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundDeviceListMethods.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundDeviceListProperties.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.DisableAllEffects.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.DisableChorusSoundEffect.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.DisableCompressorSoundEffect.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.DisableDistortionSoundEffect.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.DisableEchoSoundEffect.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.DisableFlangerSoundEffect.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.DisableGargleSoundEffect.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.DisableI3DL2ReverbSoundEffect.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.DisableParamEqSoundEffect.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.DisableWavesReverbSoundEffect.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableChorusSoundEffect_overload_1.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableChorusSoundEffect_overload_2.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableChorusSoundEffect_overloads.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableCompressorSoundEffect_overload_1.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableCompressorSoundEffect_overload_2.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableCompressorSoundEffect_overloads.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableDistortionSoundEffect_overload_1.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableDistortionSoundEffect_overload_2.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableDistortionSoundEffect_overloads.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableEchoSoundEffect_overload_1.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableEchoSoundEffect_overload_2.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableEchoSoundEffect_overloads.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableFlangerSoundEffect_overload_1.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableFlangerSoundEffect_overload_2.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableFlangerSoundEffect_overloads.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableGargleSoundEffect_overload_1.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableGargleSoundEffect_overload_2.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableGargleSoundEffect_overloads.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableI3DL2ReverbSoundEffect_overload_1.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableI3DL2ReverbSoundEffect_overload_2.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableI3DL2ReverbSoundEffect_overloads.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableParamEqSoundEffect_overload_1.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableParamEqSoundEffect_overload_2.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableParamEqSoundEffect_overloads.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableWavesReverbSoundEffect_overload_1.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableWavesReverbSoundEffect_overload_2.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.EnableWavesReverbSoundEffect_overloads.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.Finalize.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.IsChorusSoundEffectEnabled.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.IsCompressorSoundEffectEnabled.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.IsDistortionSoundEffectEnabled.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.IsEchoSoundEffectEnabled.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.IsFlangerSoundEffectEnabled.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.IsGargleSoundEffectEnabled.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.IsI3DL2ReverbSoundEffectEnabled.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.IsParamEqSoundEffectEnabled.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.IsWavesReverbSoundEffectEnabled.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControl.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControlConstructor.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControlMembers.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControlMethods.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEffectControlProperties.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.AddFileFactory.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.AddSoundSourceAlias.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.AddSoundSourceFromFile_overload_1.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.AddSoundSourceFromFile_overload_2.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.AddSoundSourceFromFile_overload_3.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.AddSoundSourceFromFile_overloads.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.AddSoundSourceFromIOStream.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.AddSoundSourceFromMemory.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.AddSoundSourceFromPCMData.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Default3DSoundMaxDistance.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Default3DSoundMinDistance.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Finalize.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.GetSoundSource_overload_1.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.GetSoundSource_overload_2.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.GetSoundSource_overloads.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.IsCurrentlyPlaying.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.IsMultiThreaded.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.LoadPlugins.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Name.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Play2D_overload_1.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Play2D_overload_2.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Play2D_overload_3.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Play2D_overload_4.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Play2D_overload_5.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Play2D_overload_6.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Play2D_overloads.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Play3D_overload_1.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Play3D_overload_2.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Play3D_overload_3.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Play3D_overload_4.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Play3D_overload_5.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Play3D_overload_6.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Play3D_overload_7.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Play3D_overload_8.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Play3D_overloads.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.RemoveAllSoundSources.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.RemoveSoundSource.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.SetAllSoundsPaused.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.SetDopplerEffectParameters.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.SetListenerPosition_overload_1.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.SetListenerPosition_overload_2.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.SetListenerPosition_overload_3.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.SetListenerPosition_overload_4.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.SetListenerPosition_overloads.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.SetRolloffFactor.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.SoundVolume.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.StopAllSounds.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.Update.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngine.internalGetNativeEngine.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngineConstructor.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngineConstructor1.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngineConstructor2.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngineConstructor3.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngineConstructor4.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngineMembers.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngineMethods.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundEngineProperties.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundMembers.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundMethods.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundProperties.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundSource.AudioFormat.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundSource.DefaultMaxDistance.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundSource.DefaultMinDistance.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundSource.DefaultVolume.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundSource.Dispose.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundSource.Finalize.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundSource.ForceReloadAtNextUse.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundSource.ForcedStreamingThreshold.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundSource.IsSeekingSupported.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundSource.Name.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundSource.PlayLength.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundSource.SampleData.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundSource.StreamMode.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundSource.getNativeSoundSource.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundSource.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundSourceConstructor.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundSourceMembers.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundSourceMethods.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundSourceProperties.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundStopEventReceiver.OnSoundStopped.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundStopEventReceiver.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundStopEventReceiverMembers.html \
    irrKlang/doc/dotnet/IrrKlang.ISoundStopEventReceiverMethods.html \
    irrKlang/doc/dotnet/IrrKlang.SampleFormat.html \
    irrKlang/doc/dotnet/IrrKlang.SoundDeviceListType.html \
    irrKlang/doc/dotnet/IrrKlang.SoundEngineOptionFlag.html \
    irrKlang/doc/dotnet/IrrKlang.SoundOutputDriver.html \
    irrKlang/doc/dotnet/IrrKlang.StopEventCause.html \
    irrKlang/doc/dotnet/IrrKlang.StreamForwarder.html \
    irrKlang/doc/dotnet/IrrKlang.StreamForwarderMembers.html \
    irrKlang/doc/dotnet/IrrKlang.StreamMode.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.CrossProduct.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.DotProduct.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.Equals.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.GetDistanceFrom.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.GetDistanceFromSQ.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.GetInterpolated.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.GetLength.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.GetLengthSQ.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.Invert.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.IsBetweenPoints.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.Length.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.LengthSQ.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.Normalize.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.SetLength.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.Set_overload_1.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.Set_overload_2.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.Set_overloads.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.ToString.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.X.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.Y.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.Z.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.op_Addition.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.op_Division.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.op_Equality.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.op_Multiply_overload_1.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.op_Multiply_overload_2.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.op_Multiply_overloads.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3D.op_Subtraction.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3DConstructor.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3DConstructor1.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3DConstructor2.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3DFields.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3DMembers.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3DMethods.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3DOperators.html \
    irrKlang/doc/dotnet/IrrKlang.Vector3DProperties.html \
    irrKlang/doc/dotnet/IrrKlang.html \
    irrKlang/doc/dotnet/IrrKlangHierarchy.html \
    irrKlang/doc/dotnet/MSDN.css \
    irrKlang/doc/dotnet/contents.html \
    irrKlang/doc/dotnet/default.html \
    irrKlang/doc/dotnet/index.html \
    irrKlang/doc/dotnet/intevent.gif \
    irrKlang/doc/dotnet/intfield.gif \
    irrKlang/doc/dotnet/intmethod.gif \
    irrKlang/doc/dotnet/intoperator.gif \
    irrKlang/doc/dotnet/intproperty.gif \
    irrKlang/doc/dotnet/ndoc.log \
    irrKlang/doc/dotnet/privevent.gif \
    irrKlang/doc/dotnet/privfield.gif \
    irrKlang/doc/dotnet/privmethod.gif \
    irrKlang/doc/dotnet/privoperator.gif \
    irrKlang/doc/dotnet/privproperty.gif \
    irrKlang/doc/dotnet/protevent.gif \
    irrKlang/doc/dotnet/protfield.gif \
    irrKlang/doc/dotnet/protmethod.gif \
    irrKlang/doc/dotnet/protoperator.gif \
    irrKlang/doc/dotnet/protproperty.gif \
    irrKlang/doc/dotnet/pubevent.gif \
    irrKlang/doc/dotnet/pubfield.gif \
    irrKlang/doc/dotnet/pubmethod.gif \
    irrKlang/doc/dotnet/puboperator.gif \
    irrKlang/doc/dotnet/pubproperty.gif \
    irrKlang/doc/dotnet/static.gif \
    irrKlang/doc/dotnet/tree.css \
    irrKlang/doc/dotnet/tree.js \
    irrKlang/doc/dotnet/treenodedot.gif \
    irrKlang/doc/dotnet/treenodeminus.gif \
    irrKlang/doc/dotnet/treenodeplus.gif \
    irrKlang/doc/readme.txt \
    irrKlang/lib/Winx64-visualStudio/irrKlang.exp \
    irrKlang/lib/Winx64-visualStudio/irrKlang.lib \
    irrKlang/media/MF-3DAYS.S3M \
    irrKlang/media/MF-PANTS.MOD \
    irrKlang/media/MF-W-90.XM \
    irrKlang/media/bell.wav \
    irrKlang/media/explosion.wav \
    irrKlang/media/getout.ogg \
    irrKlang/media/license.txt \
    irrKlang/media/ophelia.mp3 \
    irrKlang/plugins/ikpMP3/license.txt \
    irrKlang/plugins/ikpMP3/readme.txt \
    irrKlang/readme.txt \
    shadow.frag \
    shadow.vert

FORMS += QGLViewer/ImageInterface.ui mainwindow.ui


CONFIG *= debug_and_release console qt opengl warn_on thread create_prl rtti
CONFIG *= C++11

DEFINES *= QGLVIEWER_STATIC
win32 {
    DEFINES *= NOMINMAX
}

win32 {
  contains ( QT_MAJOR_VERSION, 5 ) {
    greaterThan( QT_MINOR_VERSION, 4) {
      LIBS *= -lopengl32
    }
  }
}

unix:!macx: LIBS += -L$$PWD/irrKlang/bin/linux-gcc-64/ -lIrrKlang

INCLUDEPATH += $$PWD/irrKlang/include
DEPENDPATH += $$PWD/irrKlang/include
